Add support for endpointaccessgateway for AWS
cloudera-labs/cloudera.cloud pull request #15
Opened 2021-06-15 12:01 UTC by guruchai

2021-06-21 18:19 UTC, wmudge requested changes
Minor changes

2021-06-21 18:19 UTC, wmudge commented on plugins/modules/env.py
> +            endpoint_access_scheme=dict(required=False, type='str')
add `choices=['PUBLIC', 'PRIVATE']` to `endpoint_access_scheme`.

2021-06-21 18:19 UTC, wmudge commented on plugins/modules/env.py
> +  endpoint_access_scheme:
add `choices` documentation entry, listing `PRIVATE` and `PUBLIC`

2021-06-21 18:19 UTC, wmudge commented on plugins/modules/env.py
> +      - (AWS) The subnets to use for endpoint access gateway.
Explicitly state these are subnet _IDs_

2021-07-13 15:22 UTC, Chaffelson approved these changes

2021-07-13 15:23 UTC, merged