Add and update CDW modules
cloudera-labs/cloudera.cloud pull request #29
Opened 2021-08-19 21:10 UTC by wmudge

Dependent on the following PRs:
* https://github.com/cloudera-labs/cdpy/pull/27
* https://github.com/cloudera-labs/cdpy/pull/28

2021-08-19 22:04 UTC, wmudge commented
Either we commit this one or #19 - but not both!

2021-08-20 15:29 UTC, wmudge commented
Note that the details returned by `cloudera.cloud.dw_cluster_info` no longer calls `cdpy.gather_clusters` as this call has different values depending on whether or not you pass in `env`. In addition, that call is out-of-scope for the module.

2021-09-08 13:07 UTC, Chaffelson requested changes
Mostly the use of bare `id` ambiguously across the modules

2021-09-08 13:07 UTC, Chaffelson commented on plugins/modules/dw_virtual_warehouse.py
> +  id:
also

2021-09-08 13:07 UTC, Chaffelson commented on plugins/modules/dw_virtual_warehouse.py
> +    id: example-virtual-warehouse-id
and here

2021-09-08 13:07 UTC, Chaffelson commented on plugins/modules/dw_virtual_warehouse.py
> +        self.id = self._get_param('id')
bare `id`

2021-09-08 13:07 UTC, Chaffelson commented on plugins/modules/dw_virtual_warehouse.py
> +        if self.id is None:
bare `id`

2021-09-08 13:07 UTC, Chaffelson commented on plugins/modules/dw_virtual_warehouse_info.py
> +  id:
bare `id`

2021-09-16 13:24 UTC, wmudge commented on plugins/modules/dw_database_catalog.py
> +  id:
I updated to use `catalog_id` as the name, with `id` as an aliases

2021-09-16 13:25 UTC, wmudge commented on plugins/modules/dw_database_catalog.py
> +        self.id = self._get_param('id')
Yep, updated this as well

2021-09-16 16:42 UTC, merged