Feature/raz
cloudera-labs/cloudera.cloud pull request #49
Opened 2022-02-11 10:36 UTC by nmarian85

Somehow the DCO signed commits are giving me headaches. Retrying.

2022-02-11 10:37 UTC, nmarian85 commented
Wow, it worked :). Took me a moment to realize that the Author name and Signed-off-by field need to be the same. Github should document that feature better.

2022-03-09 17:52 UTC, wmudge commented on plugins/modules/datalake.py
> +      - Flag indicating if Ranger RAZ fine grained access should be enabled for the datalake
Also should add entry for the response, which now includes `enableRangerRaz`

2022-03-09 17:53 UTC, wmudge commented on plugins/modules/datalake.py
> +            payload.update(enableRangerRaz=self.raz)
Not supported yet in GCP last time I checked, so will need a guard condition

2022-03-09 17:54 UTC, wmudge requested changes
Need to add a guard condition for GCP deployments and update the general response fields to include the RAZ entry

2022-07-21 21:10 UTC, wmudge commented
Handled by #55

2022-07-21 21:10 UTC, closed without merging